title : Xiaodong Qi's academic NoteBlog
tagline: Exploring Quantum World
author :
  name : Xiaodong Qi
  givenName: Xiaodong
  familyName: Qi
  ChineseName: 戚晓东
  twitter: i2000s
  github: i2000s
  email : i2000s@hotmail.com
url: http://i2000s.github.io

permalink: /:year/:month/:day/:title.html
redirects: yes

#gems:
#  - jekyll-pandoc
gems: ['jekyll-twitter-plugin']

encoding: utf-8

## Markdown Parser
markdown: pandoc
markdown_ext: markdown,md
pandoc:
   extensions: [smart, mathjax]

highlighter: pygments
source: .
lsi: True

pageviews: yes    ## toggle on sidebar pageviews
gitstamps: yes
username: i2000s
repo: i2000s.github.io # used in linking history and auto-deploy the site on travis-CI.

twitter_api: yes
analytics: UA-46730871-1 ## Google Analytics key (in _includes/analytics.html)

baseurl: '/'

markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Publications. Ref: http://tuxette.nathalievilla.org/?p=1426
# http://eric-tramel.github.io/working-automated-publications/
# csl style: https://github.com/citation-style-language/styles
gems:
  - "jekyll/scholar"
scholar:
  style: assets/APS.csl
  locale: en

  sort_by: year
  order: descending

  source: assets
  bibliography: QiPublications
  bibliography_template: bibtemplate

  replace_strings: true

  details_dir:    pubs
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .travis.yml
  - _posts/*.Rmd
  - _posts/source
  - assets/_bootstrap-3.1.1
  - Dockerfile
  - build.R
  - _cache
  - Makefile
  - deploy.sh
  - fig.yml
  - _posts/source/
  - _posts/_private/
