title : ICIQ - Information, Computation, Intelligence and Quantum
tagline: Getting ready for the Quantum Times
author :
  name : ICIQ Community
  givenName: ICIQ
  familyName: Community
  twitter: ICIQ_project
  github: ICIQ
  email : iciqproject@gmail.com
  gplus: communities/112872767737673370045
  facebook: groups/488750657941233/
  ghorgs: # Used in the Javascript of Community page to pull out github repos.
    - name: ICIQ
url: http://iciq.github.io
disqus:
  sitename: iciq-project
  channel:
    - name: Quantum Information and Computing
      shortname: quantuminformationandcomputing
    - name: Quantum Optics
      shortname: quantumoptics
addthis:
  pubid: ra-54f627261121ebae
navigation: # For the navigation menu. Don't use index.html. urls should end with a directory.
  - text: Home
    url: /
  - text: Observe
    url: /observe.html
  - text: Entangle
    url: /entangle.html
  - text: More
    url: /more.html

permalink: /:year/:month/:day/:title.html
redirects: yes
encoding: utf-8
pageviews: no    ## toggle on sidebar pageviews
twitter_api: yes
analytics: UA-46730871-1 ## Google Analytics key UA-46730871-1(in _includes/analytics.html and search.html)
baseurl: '/'
lsi: True # Possibly for generating related posts with gsl and classifier packages.

# GitHub information of this site. Used for extracting commit history of posts.
gitstamps: yes
username: i2000s
orgname: ICIQ
repo: iciq.github.io # used in linking commit history and auto-deploy the site on travis-CI.
sourcebranch: dev # used in linking commit history.

source: .
gems:
  - jekyll-pandoc
  - 'jekyll-twitter-plugin'
# Publications. Ref: http://tuxette.nathalievilla.org/?p=1426
# http://eric-tramel.github.io/working-automated-publications/
# csl style: https://github.com/citation-style-language/styles

#gems:
#  - "jekyll/scholar"
#scholar:
#  style: assets/APS.csl
#  locale: en
#
#  sort_by: year
#  order: descending
#
#  source: assets
#  bibliography: QiPublications
#  bibliography_template: bibtemplate
#
#  replace_strings: true
#
#  details_dir:    pubs
#  details_layout: bibtex.html
#  details_link:   Details
#
#  query: "@*"



## Markdown Parser
markdown: pandoc
markdown_ext: markdown,md
pandoc:
   extensions:
     - smart
     - mathjax

#highlighter: pygments

#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#highlighter: pygments

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .travis.yml
  - _posts/*.Rmd
  - _posts/source
  - assets/_bootstrap-3.3.6
  - Dockerfile
  - build.R
  - _cache
  - Makefile
  - deploy.sh
  - fig.yml
  - _posts/source/
  - _posts/_private/
