title : ICIQ - Information, Computation, Intelligence and Quantum
tagline: Getting ready for the Quantum Times
author :
  name : ICIQ Community
  givenName: ICIQ
  familyName: Community
  twitter: ICIQ_project
  github: ICIQ
  email : iciqproject@gmail.com
  gplus: communities/112872767737673370045
  facebook: groups/488750657941233/
  ghorgs: # Used in the Javascript of Community page to pull out github repos.
    - name: ICIQ
    - name: CQuIC
    - name: JuliaQuantum
    - name: JuliaCN
url: http://iciq.github.io
baseurl: ''
disqus:
  sitename: iciq-project
  channel:
    - name: Quantum Information and Computing
      shortname: quantuminformationandcomputing
    - name: Quantum Optics
      shortname: quantumoptics
addthis:
  pubid: ra-54f627261121ebae
navigation: # For the navigation menu. Don't use index.html. urls should end with a directory.
  - text: Home
    url: /
  - text: Observe
    url: /observe/
  - text: Entangle
    url: /entangle/
  - text: More
    url: /more/

permalink: /:year/:month/:day/:title.html
redirects: yes
encoding: utf-8
pageviews: no    ## toggle on sidebar pageviews
twitter_api: yes
analytics: UA-46730871-1 ## Google Analytics key UA-46730871-1(in _includes/analytics.html and search.html)
baiduid: yIVnlNh83X # Baidu site verification ID. Used in metadata.html.
baidutongji: a651398a55cb7e55a38cec494ce906a1 # This is for collecting statistical data of visit from Baidu. Used in analytics.html.
lsi: True # Possibly for generating related posts with gsl and classifier packages.
show_drafts: false

# GitHub information of this site. Used for extracting commit history of posts.
gitstamps: yes
username: i2000s
orgname: iciq # This is used to identify the category of GitHub repository. Use username for personal repository.
repo: iciq.github.io # used in linking commit history and auto-deploy the site on travis-CI. The repository address will be identified as https://username:GH_TOKEN@github.com/orgname/repo.git defined in Rakefile.
sourcebranch: dev # used in linking commit history.

source: .
gems:
  - jekyll-pandoc # Require to install pandoc, pandoc-citeproc and even pandoc-crossref before hand.
  - 'jekyll-twitter-plugin'
# Publications. Ref: http://tuxette.nathalievilla.org/?p=1426
# http://eric-tramel.github.io/working-automated-publications/
# csl style: https://github.com/citation-style-language/styles

#gems:
#  - "jekyll/scholar"
#scholar:
#  style: assets/bibliography/APS_Qi.csl
#  locale: en
#
#  sort_by: year
#  order: descending
#
#  source: assets/bibliography
#  bibliography: QiPublications
#  bibliography_template: bibtemplate
#
#  replace_strings: true
#  join_strings: true
#
#  use_raw_bibtex_entry: false
#  bibtex_filters:
#    #- superscript
#    - latex
#    #- markdown
#
#  details_dir:    pubs
#  details_layout: noDetailsPage.html #bibtex.html # Use bibtex.html layout to generate details pages for bibtex entries. Use other non-existing names otherwise.
#  details_link: Details
#
#  query: "@*"



## Markdown Parser
markdown: pandoc
markdown_ext: markdown,md
pandoc:
   extensions:
     - smart
     - mathjax
     - csl: assets/bibliography/APS_Qi.csl # The citation style file. Optional and may not work properly.
     - bibliography: assets/bibliography/References.bib # BibTex source. Optional.
     - email-obfuscation: javascript
     #- from: markdown+autolink_bare_uris

#highlighter: pygments

#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#highlighter: pygments

## Have pages & posts use their default layouts, respectively
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .travis.yml
  - _posts/*.Rmd
  - _posts/source
  - Dockerfile
  - build.R
  - _cache
  - Makefile
  - deploy.sh
  - fig.yml
  - _posts/_private/
  - _config/
  - _TEMP/
